apiVersion: org.ethzero.cloud/v1alpha1
kind: Team
metadata:
  labels:
    app.kubernetes.io/name: team
    app.kubernetes.io/instance: team-sample
    app.kubernetes.io/part-of: team-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: team-controller
  name: team-sample
spec:
  groupName: foogroup
  roleName: team-ns-role
  roleBindings:
    # roleName: namespaceName
    - roleName: postgres-rw
      nameSpace: pgo-team-sample
